name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"  # Executa a cada 12 horas
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      # Gera a animação da cobrinha
      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: lecristina  # Coloque seu nome de usuário
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Publica a animação no GitHub Pages
      - name: Push Snake Animation to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
